### ISSUE TITLE
Activate a Kodi mode to avoid saying the activation phrase to each command

### ISSUE THREAD

**Issue by bisca330** [m0ngr31/kodi-alexa#268] opened 2018-06-28 13:22 UTC
Hello,

I am a french who discovers Alexa with the arrival of the game Echo in France. I have been using Kodi for a long time and I find your project very interesting. I will also try to put it up soon at home.

Here is my request: Would it be possible to let the Kodi mode activate to avoid saying the activation phrase to each command. For example the activation phrase could be: "Alexa, kodi mode enabled". Then we can pass the voice commands the time of the use of Kodi without mentioning the activation phrase and we could end the use of Kodi with for example: "Alexa, Kodi mode disabled".

I know it's possible with the Jarvis voice assistant (https://www.openjarvis.com/plugins/kodi), but can we do it with Alexa?

Regards,

Micky

**Comment by jingai** [comment] 2018-06-28 13:42
It does do this automatically after receiving certain commands:

```
PlayerMove(Up|Down|Left|Right)
PlayerRotate(Counter)?Clockwise
PlayerZoom(Hold|Reset)
PlayerZoom(In|Out)(MoveUp|MoveDown|MoveLeft|MoveRight)?
Menu
Home
Select
Page(Up|Down)
Left
Right
Up
Down
Back
View(Movies|Shows|MusicVideos|Music|Artists|Albums)
View(Audio|Video)?Playlist(Recent)?
Shutdown
Hibernate
Suspend
EjectMedia
AddonGlobalSearch
WhatNew(Albums|Movies|Shows|Episodes|Albums)
Help
```

And maybe some I missed.. basically, most all of the navigation-type Intents will leave the session open.

You can also initiate a session by just asking `Alexa, open Kodi`

**Comment by jingai** [comment] 2018-06-28 13:44
More simply stated, any Intent that initiates playback of media will close the session.  This is by design, as we found that Alexa would falsely respond to the audio from the media being played back, resulting in unexpected actions taken.

**Comment by bisca330** [comment] 2018-06-28 14:02
Thank you for your answers.

I think I understood, but to be certain it means that as soon as I start playing an audio or video file the session will be closed. But as long as I do not run any media I can navigate in kodi without pronouncing the activation phrase before each voice command.

Did I understand well ?

Micky

**Comment by jingai** [comment] 2018-06-28 23:03
Yes, the session will be closed if you initiate media playback via the skill.

**Comment by jingai** [comment] 2018-06-29 01:50
If you're satisfied with this answer, please close this issue :)

**Closed as completed** 2018-06-29 08:00 UTC
