### ISSUE TITLE
Update Slot Types to Amazon Standard Names (i.e. AMAZON.Movie)

### ISSUE THREAD

**Issue by AgileHumor** [m0ngr31/kodi-alexa#116] opened 2017-02-19 23:58 UTC
From Emby Forum Post:
https://emby.media/community/index.php?/topic/44330-lets-talk-amazon-echo-and-emby-what-we-would-actually-need-to-do/page-6#entry421004

`Try to avoid using custom slots and use Amazon's built in types 
 
For movie names, use type "AMAZON.Movie". 
 
You only need one intent "playMovie" with a slot for title (type = AMAZON.Movie) There is even a slot type for tv episode titles!! AMAZON.TVEpisode`

Amazon Reference
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#list-types

**Comment by jingai** [comment] 2017-02-20 04:03
The problem is that I believe these are currently only supported for US customers.

**Comment by jingai** [comment] 2017-02-20 04:05
See #82 (which I believe this is a duplicate of).

**Comment by digiltd** [comment] 2017-02-21 12:02
As jingai said, only US Skills are supported at the moment. The built-in library is also only defined as a [developer preview](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/built-in-intent-library#availability) (though they haven't made any changes so far since it was made available Dec 7th 2016)

**Comment by AgileHumor** [comment] 2017-02-26 17:06
Makes sense, thanks all!

PS - Sorry for the dupe

**Closed as completed** 2017-02-28 15:14 UTC
