### ISSUE TITLE
Feature Request (improved PlaySong)

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#168] opened 2017-05-24 06:29 UTC
Could it be made that if I ask for a song kodi would create a short playlist with all versions of it? I mean I do have quite a few songs in different versions (live/acapella/studio/performed by another artist/...). If I ask for a song kodi or the skill will take the first match (I guess) and pretty often that's not the version I wanted to listen to.

**Comment by jingai** [comment] 2017-05-24 14:40
This is the same problem you get with Amazon's own music service though.  I don't think I would want this to be the default behavior for ListenToSong, but if we could create a new utterance for it that is distinct enough, maybe..

**Comment by digiltd** [comment] 2017-05-25 12:32
@mcl22 Interesting scenario, as you know you have multiple versions and you know which of those versions you want to listen to, could you make your initial "play song" request more specific?

**Comment by mcl22** [comment] 2017-05-25 13:30
Well in some cases I guess I could if I new the exact title like "atemlos", "atemlos (Acapella-Version)" and "atemlos (extended dance version 2015". But I don't know them :)
Another problem is that I also have the same songs on different albums. Like "Freiheit" by Westernhagen. I do have this song 5 times and it's always only called "Freiheit". I do have tomention that all of my mp3s are tagged with Picard and I don't change those tags. So if Musicbrainz calls it only "Freiheit" it is only "Freiheit" in my library. Eg Westernhagen has an album called "Live" and all songs on this album are live recordings but it's not tagged into the title tag.
And if that was not enough there's another artist "Unheilig" who also has a song called "Freiheit". In this sample (I haven't tried it) with just PlaySong it could happen that not even the right artist would be choosed for my demand :)
Last example and that is the one that actually made me open this request:
There's a song called "Tränen lügen nicht". It's originally performed by an artist called "Michael Holm". When I had Alexa play that song she chose a version from Otto Waalkes who is a german comedian. I didn't even know that I do have this song in a version performed by him :) But that was defenitly not the version I wanted to listen to :)

**Comment by mcl22** [comment] 2017-05-25 13:32
Ah, and "play song by Michael Holm" didn't work because he's no album artist and so Alexa can't find him what refers to #170.

**Comment by jingai** [comment] 2017-05-25 14:10
Even Amazon doesn't do this though, and I think it's just one of those fundamental shortcomings of a VUI. If you can't find it by being more specific, you're probably better off using a different (visual)  interface to get at it.

**Comment by digiltd** [comment] 2017-05-25 15:46
I completely agree, using voice would be incredibly tedious 

"Alexa, play Freiheit by Westernhagen"

"I have found 5 titles matching that name, would you like me to list them?

"yes"

"1 - Freiheit [Wunschkonzert Edit] by Westernhagen from the album Wunschkonzert
2- Freiheit (Live) [Remastered] by Westernhagen from the album Keine Zeit
3 - Freiheit by Westernhagen (WEA) from the album Westernhagen
4 - Freiheit (Remastered) by Westernhagen (WEA) from the album Westernhagen (Remastered)
5 - Freiheit (Remastered) by Westernhagen (WEA) from the album So Weit - Best Of"

"Which one would you like to listen to?"

(The list alone is 30 seconds long when ran through a text to speech tool)

Or you could have 

"Alexa, play Freiheit by Westernhagen"

"I have found 5 titles matching that name, would you like me to list them?

"yes"

"Freiheit [Wunschkonzert Edit] by Westernhagen from the album Wunschkonzert.
Do you want me to play this track or continue the list?"

"continue"

"Freiheit (Live) [Remastered] by Westernhagen from the album Keine Zeit
Do you want me to play this track or continue the list?"

"continue"
  
... etc etc


Whilst voice is great for some tasks, for browsing information it is horrible. That is why people get so disappointed with voice services when they try to "google" something and it doesn't work. They are used to typing something in and seeing a whole page of results at a glance, sometimes the answer appears in the search result description and they get it instantly. A computer doesn't know how to do this, sitting and waiting for her to read every search result is not realistic. 

You could try uploading all your music to Amazon Music and seeing if that gives you better results as for matched uploaded it will use it's own database, it's free for 250 songs (up to 250,000 songs for £21.99/year).

**Comment by jingai** [comment] 2017-05-25 16:07
For reference, I actually subscribe to Amazon Music Unlimited and see this same 'problem' there.  The issue is, quite simply, that she doesn't (and really, cannot) know to which version I'm referring.

Perhaps Amazon will come up with some elegant way to solve this, but for now, I'm inclined to say that our behavior should match Amazon's where possible.

**Comment by mcl22** [comment] 2017-05-25 19:57
Oh I am sorry. I obviously  didn't  make it clear what I am looking for. I would be glad if in cases that there are several versions of a song kodi would just create a play list with all those versions and play them. So I could listen to all of them or just skip via remote. Sorry for misunderstanding  :)

**Comment by jingai** [comment] 2017-05-25 20:49
I understood what you wanted -- and I think @digiltd did too, but was offering up alternative ways we might go about implenting this -- but I don't think it's the right thing to do either way.  Even with what you want, it involves "Alexa, tell kodi to skip" repeatedly until you get what you want.

IMHO, the "right answer" here is to simply try to be more specific, and if you can't get to it that route, use Kodi's own interface to do it.

FWIW, try just adding "live" or "acapella" to your titles and see what happens.  The fuzzy matching might get it.

**Comment by jingai** [comment] 2017-06-03 03:08
Closing this as the way to really 'fix' this is to keep improving the fuzzy matcher.  If I ask for a song, it should play a song, not a bunch of songs :)

**Closed as completed by jingai** 2017-06-03 03:08 UTC
