### ISSUE TITLE
Slot Generator doesn't remove "

### ISSUE THREAD

**Issue by StormTrooper** [m0ngr31/kodi-alexa#133] opened 2017-04-01 19:13 UTC
Slot generator does not remove " characters which AWS then complains about as its a illegal character

**Comment by jingai** [comment] 2017-04-02 15:12
You're right, though I could have sworn we took care of this at one point.. odd.

**Comment by jingai** [comment] 2017-04-02 22:08
This is a duplicate of #97.

**Closed as completed by jingai** 2017-04-02 22:08 UTC
Labels: bug, duplicate
