### ISSUE TITLE
Tv Shows with a (written) number in title

### ISSUE THREAD

**Issue by nawo69** [m0ngr31/kodi-alexa#39] opened 2016-10-23 21:48 UTC
Hi shows that have a written number in the title aren't found for Example Brooklyn Nine Nine and Hawaii Five-O.

In the log it is searching for Brooklyn 99 and hawaii 5 o

**Comment by m0ngr31** [comment] 2016-10-25 23:01
This one will be a little tricky, but I'll look into it.

**Comment by digiltd** [comment] 2016-10-31 10:06
@nawo69 Alexa is doing things correctly, it is the way the show is titled and then marketed that is the problem.

When saying "Hawaii Five-O" you are probably (and understandably) saying "five oh",  but the "oh" is actually a "zero". It might work if you said "hawaii five zero"

Fun fact from wikipedia: The title of the new show uses a zero ("0") rather than the letter "O" used in the 'Five-O' of the original.

The same is true with "double oh seven", it should be pronounced "zero zero seven"

You could try changing the titles in your library to what Alexa thinks you are saying.

**Comment by nawo69** [comment] 2016-10-31 10:57
@digiltd it is the Five in Hawaii Five 0 that is causing the issue not the 0 anyway :)

Changing the titles might work but on a automatic download/renaming system would have to do this manually every time a episode is downloaded.

It isn't a massive issue just thought it was worth flagging up

**Comment by jingai** [comment] 2016-10-31 11:29
The skill could try querying the database in different ways, but there'd be a speed tradeoff there too.

Alternatively -- at least for now -- you can always add it to your SHOWS slot.

**Comment by jingai** [comment] 2016-10-31 11:30
FWIW, this becomes a much larger problem if we start thinking about internationalization too...

**Comment by danielmasur** [comment] 2016-10-31 11:47
Not too sure it actually would because all the shows names are pronounced the English way, at least in Germany. It's "Haway feif oh" ;)

**Comment by jingai** [comment] 2016-10-31 11:49
@ausweider , I don't mean for this particular show.  I mean for shows with titles in other languages that might have a similar problem.  Granted, this is already a problem for English speakers that watch foreign shows/films.

**Comment by nawo69** [comment] 2016-10-31 11:56
@jingai 

> Alternatively -- at least for now -- you can always add it to your SHOWS slot.

I already have them in my Shows slot; For example I have: Brooklyn Nine-Nine

**Comment by freemans13** [comment] 2016-10-31 12:15
I have been struggling with a similar issue for PVR channel names. In the UK the channel names are often abbreviated by the provider. 'Horror chnl' rather than 'horror channel'. I'm not ever going to say 'alexa, ask cody to watch horror chnl'. 

What I implemented was a list of 'aliases' that act as alternative names for certain channels. The issue is that this is a hard coded list. One solution I was toying with was to create a user friendly webapp to manage this list. The problem is this complicating things. I love the idea of a simple lambda function.

**Comment by jingai** [comment] 2016-11-09 22:48
Might be solved by PR #54.  Will verify.

**Comment by jingai** [comment] 2016-11-09 23:44
PR #54 solves the problem for at least Hawaii Five-O for me.

@nawo69, can you test with PR #54 and confirm?

**Comment by jingai** [comment] 2016-11-09 23:48
@freemans13, I'd also really be interested to know if it removes the need for the channel aliases, if you don't mind giving it a go.

**Comment by nawo69** [comment] 2016-11-10 15:05
@jingai Yip that is working fine for me with Brooklyn Nine Nine and Hawaii Five-O great work guys

**Comment by jingai** [comment] 2016-11-11 13:00
Just awaiting input from @freemans13 before closing.

**Comment by freemans13** [comment] 2016-11-16 01:08
Thankfully I've been using fuzzywuzzy too :)
I've not checked the specific Brooklyn Nine Nine and Hawaii Five-O scenarios (I think they could work actually). The more challenging part for me is 'BBC Northen Ireland'->'BBC NI', 'BBC 2'->'BBC Two Eng', 'Horror Channel plus 1'->'Horro ch+1'.
I'll take a closer look.

**Comment by jingai** [comment] 2016-11-16 01:15
@freemans13, it'd be useful to see what we can solve without aliases.  If you could test calling for channels in your area without aliases and post back here with the results, I'd appreciate that.

**Comment by jingai** [comment] 2016-11-17 19:51
Closing this since the specific problem referenced in this Issue has been resolved.  We can continue discussion about the PVR stuff on PR #47.

**Closed as completed by jingai** 2016-11-17 19:51 UTC

**Comment by freemans13** [comment] 2016-11-28 01:02
Finally! I've run some tests that don't use aliasing.
I can report Brooklyn Nine-Nine and Hawaii Five-O work well without aliasing (using fuzzywuzzy matching only).
Where fuzzywuzzy can't help is where the PVR channel name coming from Kodi is abbreviated.
Examples:
BBC Two Eng
(should be BBC Two England)
horror ch+1
(Horror Channel plus 1)
True Ent
(True Entertainment)
BBC One S West
(BBC One South West)

**Comment by freemans13** [comment] 2016-11-28 01:05
My fuzzywuzzy logic is already on the branch BTW.
What i'd like is a steer on 
- the 'media type'
- the utterances
